### PR TITLE
add linux definitions patch

### PR DESCRIPTION
**Pull request by John-Ted**
Add patch to change define values to the values currently used by the Linux kernel

### CODE REVIEW

**Review by mogasergiu — COMMENTED** [review]
Hi, thanks for the patch!

I think it would be better to change the headline of the commit message to be aligned with the other commits in the same directory. Something like:
```
patches:  Align `TCP_KEEP*` macro values with those of Linux
```

Also provide a more detailed description of what you did and why. Either do it in the message of the patch or in this commit's message (preferrably both) and end it with a dot.

**Review by LucaSeri — APPROVED** [review]
Hi @John-Ted! Thank you for this patch, I did a test build with nginx and it looks good to me.

Reviewed-by: Luca Seritan [luca.seritan@gmail.com](mailto:luca.seritan@gmail.com)

**Review by mogasergiu — APPROVED** [review]
Reviewed-by: Sergiu Moga <sergiu.moga@protonmail.com>

**Review by eduardvintila — APPROVED** [review]
Let's get this in. Thanks, @John-Ted!

Approved-by: Eduard Vintilă <eduard.vintila47@gmail.com>

**Pull request closed without merging**
